[package]
name = "token"
version = "1.0.0"
authors = ["code-xD (shivansh586@gmail.com)"]

[addresses]
core = "_"
workflow = "_"
publisher = "_"
aptos_framework = "0x1"

[dev-addresses]
core = "0xb00b2aef1ffae7256e4fdc345903a6102e7107d9b1ed96a451ad6c110347ce78"
token = "0x1001"
publisher = "0x0a6f65c5389cb25206b0778b0411728663f1533da8a51f36d5b14db16b18dbc4"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.core]
local = "../core"

[dev-dependencies]
