[package]
name = "core"
version = "1.0.0"
authors = ["code-xD (shivansh586@gmail.com)"]

[addresses]
core = "_"
publisher = "_"
aptos_framework = "0x1"

[dev-addresses]
core = "0x2"
publisher = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
